### ISSUE TITLE
Null 'path' when prebuilding

### ISSUE THREAD

**Issue by crieggalder** [achorein/expo-share-intent-demo#22]
Hey, thanks for the great work on this guide. Really appreciate you putting it together.

Here's the error I'm seeing after `expo prebuild`:

```
✖ Config sync failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/chris/go/campfire/node_modules/xcode/lib/pbxProject.js:1681:38)
    at correctForResourcesPath (/Users/chris/go/campfire/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/chris/go/campfire/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/chris/go/campfire/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/chris/go/campfire/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async action (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:21)
    at async interceptingMod (/Users/chris/go/campfire/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
```

Some info that may or may not be relevant:
- Expo 49
- I'm in a yarn v1 workspace with my Expo app located at /packages/app, and package.json files at /package.json and /packages/app/package.json.
- plugins and patches dirs copied to /plugins and /patches, not to /packages/app/*
- /packages/app/package.json postinstall: `expo-yarn-workspaces postinstall && patch-package`
- `postinstall-postinstall` package not installed
- app.config.js plugins section:
```
        plugins: [
            [
                'onesignal-expo-plugin',
                {
                    // ...some details
                },
            ],
            [
                'expo-build-properties',
                {
                    ios: {
                        flipper: true,
                    },
                },
            ],
            // ...some other plugins
            [
                'expo-config-plugin-ios-share-extension',
                {
                    activationRules: {
                        NSExtensionActivationSupportsWebURLWithMaxCount: 1,
                        NSExtensionActivationSupportsWebPageWithMaxCount: 1,
                        NSExtensionActivationSupportsImageWithMaxCount: 1,
                        NSExtensionActivationSupportsMovieWithMaxCount: 1,
                    },
                },
            ],
            [
                './plugins/withAndroidShareExtension/index',
                {
                    androidIntentFilters: ['text/*', 'image/*', 'video/*'],
                },
            ],
        ],
```

**Comment by achorein** [comment]
For iOS, it seems you don't apply the [xcode+3.0.1.patch](https://github.com/achorein/expo-share-intent-demo/blob/main/patches/xcode%2B3.0.1.patch) patch, the error it's directly relative to this patch.

For Android is something else but looks like a environment problem.

**Comment by achorein** [comment]
@MarekBodingerBA can you open an other issue ?
Did you use the `yarn prebuild` command. can you try with a `yarn clean` ?

**Comment by crieggalder** [comment]
Sorry @achorein, are you saying you think the error is because the xcode patch isn't being applied, or are you saying that I should not apply the patch to avoid the error?

**Comment by achorein** [comment]
patch it's a requirement, i think your xcode patch it's not applied

**Comment by nathansbird** [comment]
@crieggalder, to add context here, I thought my patch was working until I realized I was using `expo prebuild` instead of `npx expo prebuild`

Using `expo` as a CLI command was using a set of node_modules that my _local project_ patches weren't being applied to.
