### ISSUE TITLE
Android building error android/gradlew exited with non-zero code: 1

### ISSUE THREAD

**Issue by petkobonev** [achorein/expo-share-intent-demo#31]
Hey, great work on this guide. Really appreciate you putting it together.

Here's the error I'm seeing after expo run:android:

✖ Error: /Users/pbonev/react/thisisdope-app/android/gradlew exited with non-zero code: 1
Error: /Users/pbonev/react/thisisdope-app/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/pbonev/react/thisisdope-app/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at Object.spawnAsync [as default] (/Users/pbonev/react/thisisdope-app/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/pbonev/react/thisisdope-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/pbonev/react/thisisdope-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/pbonev/react/thisisdope-app/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.Some info that may or may not be relevant:

Expo 49
I'm in a yarn v1 workspace with my Expo app located at /packages/app, and package.json files at /package.json and /packages/app/package.json.
plugins and patches dirs copied to /plugins and /patches, not to /packages/app/*
/packages/app/package.json postinstall: expo-yarn-workspaces postinstall && patch-package
postinstall-postinstall package not installed
app.config.js plugins section:

**Comment by achorein** [comment]
can you give the output of the following command `npx react-native info` ?
do you have any issue with the demo, it sounds like an integration on your own project problem.

**Comment by petkobonev** [comment]
Yeah, i have the integration issue, here is the output:

`System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M2
  Memory: 76.80 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.9.0
    path: ~/.nvm/versions/node/v19.9.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/react/thisisdope-app/node_modules/.bin/yarn
  npm:
    version: 9.6.3
    path: ~/.nvm/versions/node/v19.9.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
/`

**Comment by achorein** [comment]
`postinstall-postinstall package not installed`
did you forget to install this deps ? `yarn add postinstall-postinstall`

**Comment by petkobonev** [comment]
It's installed, nothing has changed.

**Comment by achorein** [comment]
after yarn install you should have this output :
![image](https://github.com/achorein/expo-share-intent-demo/assets/6529851/c36f4ef2-ce65-4e81-9f68-3f49948945f8)

and this after prebuild: 
![image](https://github.com/achorein/expo-share-intent-demo/assets/6529851/6b1a3bb0-eaf1-4545-8cec-760ef85372a3)

you error log message is incomplete and don't give the main error, I need the initial error before `exited with non-zero code: 1` in order to help you.

**Comment by petkobonev** [comment]
Yes i have this outputs, but when try prebuild it gives me this ->
`yarn run v1.22.19
$ /Users/pbonev/react/thisisdope-app/node_modules/.bin/expo prebuild
✔ Created native projects | /android, /ios already created | gitignore skipped
› Using current versions instead of recommended react-native@0.72.6.
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using yarn
> yarn install
⠙ Config syncing************ scheme thisisdope
✖ Config sync failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/pbonev/react/thisisdope-app/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/pbonev/react/thisisdope-app/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/pbonev/react/thisisdope-app/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/pbonev/react/thisisdope-app/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:23)
    at async interceptingMod (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/pbonev/react/thisisdope-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by achorein** [comment]
it seems that your `xcode+3.0.1.patch` has not been applied (like #22).
you can verify in this file : `node_modules/xcode/lib/pbxProject.js`, you should have `if (project.pbxGroupByName(group)&&project.pbxGroupByName(group).path)` on line 1681

**Comment by achorein** [comment]
Duplicate of #22

**Comment by achorein** [comment]
`yarn patch-package` will apply all patches

that's why we got the postinstall in the `package.json`
```json
  "scripts": {
    ...
    "postinstall": "patch-package"
  }
  ```

**Comment by petkobonev** [comment]
Yep, it worked,
![image](https://github.com/achorein/expo-share-intent-demo/assets/50277004/6012c6da-2fc3-47cc-a770-33a7065235ca)
After applying the patch and prebuild execution, ive got again the same error 
![image](https://github.com/achorein/expo-share-intent-demo/assets/50277004/474b2987-8b6c-4df4-bb84-f5cb0e23e2f4)

**Comment by achorein** [comment]
after the patch you need to clean up expo prebuild with : `expo prebuild --no-install --clean`

**Comment by petkobonev** [comment]
Yep i did it, still the same -> 
![image](https://github.com/achorein/expo-share-intent-demo/assets/50277004/5e2e2f3a-498c-4897-82dd-fb1a2a56b148)

**Comment by achorein** [comment]
can you check your `android/gradle.properties`, should have this at the end of the file :  

```properties
android.kotlinVersion=1.6.10
```

if it's already the case, you can try to change the version like this in the `app.json` (clean prebuild)
```json
  "plugins": [
      [
        "./plugins/withAndroidShareExtension/index",
        {
          ...
          "androidExtraBuildProperties": { 
             "kotlinVersion": "1.8.10"
          },
        }
      ],
  ],
 ```

**Comment by petkobonev** [comment]
Yes the kotlin version is same as you described|
```javascript
android.kotlinVersion=1.6.10
``` 

I applied the 

```javascript
  [
        "./plugins/withAndroidShareExtension/index",
        {
          "androidIntentFilters": ["text/*", "image/*"],
          "androidExtraBuildProperties": {
            "kotlinVersion": "1.8.10"
          }
        }
      ],
```
And still got the same issue.

**Comment by achorein** [comment]
:/ 
seems related to your java version, you are using java 20.
Retry with java 18 
(here for more information : https://stackoverflow.com/questions/67240279/could-not-open-settings-generic-class-cache-for-settings-file)

**Comment by achorein** [comment]
feel free to reopen if the problem persist

**Comment by joshmohrer** [comment]
Try adding this to your package.json

 "overrides": {
    "@expo/config-plugins": "~7.8.4"
  },

**Comment by wodin** [comment]
Adding resolutions/overrides for `@expo/config-plugins` is usually a bad idea. The `expo` package should pull in the correct version. If there's something else trying to pull in some other version, then that should be fixed.

**Comment by achorein** [comment]
i'm working on new npm package which use a native module for android. Still in beta but you can give it a try for expo 50   https://www.npmjs.com/package/expo-share-intent
