### ISSUE TITLE
Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by joshmohrer** [achorein/expo-share-intent-demo#38]
**Describe the bug**

When I pre-build I get this error, seemingly related to expo-config-plugin-ios-share-extension.
If I comment this out of my app,.json the app builds fine.

```
[
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
            "NSExtensionActivationSupportsImageWithMaxCount": 1,
            "NSExtensionActivationSupportsMovieWithMaxCount": 1
          }
        }
      ]
```

Thank you so much!

✔ Cleared android, ios code
✔ Created native directories
✔ Updated package.json | no changes
⠙ Running prebuild************ scheme undefined
✖ Prebuild failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/joshuamohrer/Coding/waveapp-clone/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:23)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js

**To Reproduce**
npx expo prebuild --clean

** Environment **
System:
  OS: macOS 14.1.2
  CPU: (16) arm64 Apple M3 Max
  Memory: 2.32 GB / 128.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.4.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Additional context**
- expo  50.0.6
- target :  iOS
- device : simulator but dev-client, expo prebuild --clean
- type: local expo build, not eas

**Comment by joshmohrer** [comment]
Putting these patches in the root fixed it :)
https://github.com/achorein/expo-share-intent-demo/tree/expo50/patches
